meta_product_name: "recll - Creator Platform"
meta_title: "recll - Take care of your fans"
meta_description: "As a content creator you need a powerful tool to manage your community."
meta_image: "cover.png"                       # should exist in `app/assets/images/`
